version : '2.0'

services:
    nginx:
        mem_limit: 4mb
        cpu_quota: 1000
        build: .
        ports:
            - "${NGINX_PORT}:80"
        expose:
            - "${NGINX_PORT}"
        env_file: 
            - .env
        logging:
            driver: journald
